### PR TITLE
l10n: zh-Hant: review & translate new strings

### PR DESCRIPTION
**Pull request by pan93412**
- [ ] This change has been discussed with the author.
- [ ] It implements / fixes issue #.

---

**Description:**
- I translated IINA with the latest `xcloc` format from Apple Xcode, instead of editing .strings directly.
- Therefore, the string seems reordered. It won't affect the actual effect.

### CODE REVIEW

**Comment by CarterLi** [comment]
Why not contribute to the official repo?

**Comment by low-batt** [comment]
The approved way to add translations is to use [IINA's instance of Crowdin](https://translate.iina.io/).

This is discussed in the "Contributing" section of the ReadMe on IINA's GitHub repository [iina/iina](https://github.com/iina/iina):

> If you'd like to translate IINA to your language, please visit [IINA's instance of Crowdin](https://translate.iina.io/). You can create an account for free and start translating and/or approving. Please do not send pull request to this repo directly, Crowdin will automatically sync new translations with our repo. If you want to translate IINA into a new language that is currently not in the list, feel free to open an issue

I know about this because I submitted a PR directly instead of going through Crowdin and was told that is discouraged as it can disrupt the system that automatically syncs translations from Crowdin.

Once the translations are in the main IINA repository they will be pulled into IINA+ when we rebase.

The main IINA repository is under active development in preparation for a new release.

**Comment by pan93412** [comment]
Well, so what should I do next? Actually it is specific for IINA+ that has fixed up some unmatched strings (for example, yt-dlp).

**Comment by low-batt** [comment]
I'll defer to @CarterLi as to how to handle cases were the translation involves text for changes that are not in the official repository.

My understanding is the plan for handling the youtube-dl / yt-dpl issue in the official repository is the new plugin system which has not been merged yet.

**Comment by CarterLi** [comment]
> Well, so what should I do next? Actually it is specific for IINA+ that has fixed up some unmatched strings (for example, yt-dlp).

Ok, let's merge this

**Pull request merged**
